server:
  port: 8080
spring:
  sql:
    init:
      mode: "always"
      data-locations: "classpath:/schema.sql"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
